hm/hm/Models/user.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public Nullable<long> phone { get; set; }
        public string adress1 { get; set; }
        public string adress2 { get; set; }
        public string gender { get; set; }
        public string type { get; set; }
        public string password { get; set; }
        public string username { get; set; }
    }
}

hm/hm/Controllers/userController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using hm.Models;
namespace hm.Controllers
{
    public class userController : Controller
    {
        // GET: user
        public ActionResult LogIn()
        {
            if (Request.Form["email_input"] != null)
            {
                Response.Redirect("~/Home");
            }

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogIn(user u)
        {
           
            return View();
        }


        public ActionResult Register()
        {
            return View();
        }

        public ActionResult review(int ID)
        {
            finalEntities context = new finalEntities();
            user uu= context.users.Single(u => u.id == ID);
            return View(uu);
        }

    }




}

hm/hm/Views/user/LogIn.cshtml
@model hm.Models.user

@{
    ViewBag.Title = "LogIn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<style>
    .container {
        margin-top: 50px;
    }

    .categories {
        display: none;
    }

    .categories-trigger {
        display: none;
    }
    label,input{
        font-family:sans-serif;
    }
</style>

<div></div>

<div class="row">
    <div class="log-form">
       
        <form class="">
            <label for="email_input">E-mail</label> <br>
            <input type="email" id="email_input" class="input">
           
            <br>
            <label for="email_input">Password</label> <br>
            <input type="email" id="password_input" class="input">
           

            <input type="submit" class="sbmt-btn" value="Send">
        </form>
    </div>
</div>
<a href="~/Views/user/LogIn.cshtml">~/Views/user/LogIn.cshtml</a>

hm/hm/Views/user/Register.cshtml
@model hm.Models.user

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}






<div class="row">
    <div class="log-form">

        <form class="">

            @using (Html.BeginForm("LogIn", "user", FormMethod.Post))
            {
                @Html.AntiForgeryToken() //csrf attack
                @Html.ValidationSummary(true)

                if (ViewBag.Massage != null)
                {
                    <div style="1px solid red">
                        @ViewBag.Massage
                    </div>
                }

                
                <label for="email_input">User Name</label> <br>
                <input type="text" id="username_input" class="input">
                @Html.ValidationMessageFor(a => a.username)
                <label for="email_input">E-mail</label> <br>
                <input type="email" id="email_input" class="input">
                @Html.ValidationMessageFor(a => a.email)
                <br>

                <label for="password_input">Password</label> <br>
                
                <input type="password" id="password_input" class="input">
                @Html.ValidationMessageFor(a => a.password)

                <label for="password_input1">Confirm Password</label> <br>
                <input type="password" id="password_input1" class="input">
                @Html.ValidationMessageFor(a => a.password)

                <input type="submit" class="sbmt-btn" value="Send">
            }

        </form>
    </div>
</div>

hm/hm/Views/user/review.cshtml
@model hm.Models.user

@{
    ViewBag.Title = "review";
}

<h2>review</h2>

<div style="padding:20px;">
    <h4>user : @Model.username</h4>
    <hr />
    <dl class="dl-horizontal">
     
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.username)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

       
       


        

    </dl>
</div>