hm/hm/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using hm.Models;
namespace hm.Controllers
{
    public class DetailsController : Controller
    {
        // GET: Details
        public ActionResult Details(int ID)
        {

            finalEntities context = new finalEntities();
            product pro = context.products.Single(p => p.id == ID);
            return View(pro);
        }

        

        public product getProduct(int ID)
        {
            finalEntities context = new finalEntities();
            product pro= context.products.Single(p => p.id == ID);
            return pro;
        }
        
    }
}

hm/hm/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using hm.Models;
namespace hm.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            //finalEntities context = new finalEntities();
            //List<category> c= context.categories.ToList();
            return View();
        }


        public void logout()
        {
            Session.Remove("userID");
            Session.Remove("userName");
            Response.Redirect("~/home.aspx");
        }
        //public ActionResult About()
        //{
        //    ViewBag.Message = "Your application description page.";

        //    return View();
        //}

        //public ActionResult Contact()
        //{
        //    ViewBag.Message = "Your contact page.";

        //    return View();
        //}
    }
}

hm/hm/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

hm/hm/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

hm/hm/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    Response.Redirect("~/home.aspx");
}

<div class="row" style="">
    
    <a href="~/home.aspx">~/home.aspx</a>
    <div class="col-sm-12 title-text" style="display:block;">Recommended For You </div>
   
    @for (int i = 0; i < 10; i++)
    {
        <div class="col-sm-5 col-md-3 white  top-sec margin-10">

            <img src="photos/camera1.jpg" />
            <div class="left-side">
                <div class="product-name">
                    @Html.ActionLink("NIKON D3300", "Details","Details")
                </div>
                <div class="by">
                    <a href="#">By:Nikon</a>

                </div><br />
                <div class="price">
                    <span class="para">$</span><span class="price-tl">599.</span><span class="price-kr">99</span>
                </div>

                <div class="rate">
                    <span><i class="fa fa-star" aria-hidden="true"></i></span>
                    <span><i class="fa fa-star" aria-hidden="true"></i></span>
                    <span><i class="fa fa-star" aria-hidden="true"></i></span>
                    <span><i class="fa fa-star" aria-hidden="true"></i></span>
                    <span><i class="fa fa-star-o" aria-hidden="true"></i></span>

                </div>
                <div class="rate-number">(2309)</div>
            </div>
        </div>
    }



</div>

<div class="row">
    <div class="col-sm-12 title-text white-color" style="display:block;">Browse History</div>


    @for (int i = 0; i < 10; i++)
    {
        <div class="col-sm-5 col-md-3 white  top-sec margin-10">

            <img src="photos/camera1.jpg" />
            <div class="left-side">
                <div class="product-name">
                    <a href="#">Nikon D3300</a>
                </div>
                <div class="by">
                    <a href="#">By:Nikon</a>

                </div><br />
                <div class="price">
                    <span class="para">$</span><span class="price-tl">599.</span><span class="price-kr">99</span>
                </div>

                <div class="rate">
                    <span><i class="fa fa-star" aria-hidden="true"></i></span>
                    <span><i class="fa fa-star" aria-hidden="true"></i></span>
                    <span><i class="fa fa-star" aria-hidden="true"></i></span>
                    <span><i class="fa fa-star" aria-hidden="true"></i></span>
                    <span><i class="fa fa-star-o" aria-hidden="true"></i></span>

                </div>
                <div class="rate-number">(2309)</div>
            </div>
        </div>
    }

</div>


<div class="row" style="">

    <div class="categories-trigger">Categories<span> <i class="fa fa-arrow-down" aria-hidden="true"></i></span></div>
    <div class="col-sm-12 title-text" style="display:block;">Recommended For You </div>

    @for (int i = 0; i < 10; i++)
    {
        <div class="col-sm-5 col-md-3 white  top-sec margin-10">

            <img src="photos/camera1.jpg" />
            <div class="left-side">
                <div class="product-name">
                    <a href="#">Nikon D3300</a>
                </div>
                <div class="by">
                    <a href="#">By:Nikon</a>

                </div><br />
                <div class="price">
                    <span class="para">$</span><span class="price-tl">599.</span><span class="price-kr">99</span>
                </div>

                <div class="rate">
                    <span><i class="fa fa-star" aria-hidden="true"></i></span>
                    <span><i class="fa fa-star" aria-hidden="true"></i></span>
                    <span><i class="fa fa-star" aria-hidden="true"></i></span>
                    <span><i class="fa fa-star" aria-hidden="true"></i></span>
                    <span><i class="fa fa-star-o" aria-hidden="true"></i></span>

                </div>
                <div class="rate-number">(2309)</div>
            </div>
        </div>
    }



</div>

<div class="row">
    <div class="col-sm-12 title-text white-color" style="display:block;">Browse History</div>


    @for (int i = 0; i < 10; i++)
    {
        <div class="col-sm-5 col-md-3 white  top-sec margin-10">

            <img src="photos/camera1.jpg" />
            <div class="left-side">
                <div class="product-name">
                    <a href="#">Nikon D3300</a>
                </div>
                <div class="by">
                    <a href="#">By:Nikon</a>

                </div><br />
                <div class="price">
                    <span class="para">$</span><span class="price-tl">599.</span><span class="price-kr">99</span>
                </div>

                <div class="rate">
                    <span><i class="fa fa-star" aria-hidden="true"></i></span>
                    <span><i class="fa fa-star" aria-hidden="true"></i></span>
                    <span><i class="fa fa-star" aria-hidden="true"></i></span>
                    <span><i class="fa fa-star" aria-hidden="true"></i></span>
                    <span><i class="fa fa-star-o" aria-hidden="true"></i></span>

                </div>
                <div class="rate-number">(2309)</div>
            </div>
        </div>
    }

</div>





@*@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@